<!DOCTYPE html>
<html class="writer-html5" lang="en" >
<head>
  <meta charset="utf-8" /><meta name="generator" content="Docutils 0.17.1: http://docutils.sourceforge.net/" />

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>minos.saga.exceptions module &mdash; Minos Microservice Saga 0.6.0 documentation</title>
      <link rel="stylesheet" href="../_static/pygments.css" type="text/css" />
      <link rel="stylesheet" href="../_static/css/theme.css" type="text/css" />
  <!--[if lt IE 9]>
    <script src="../_static/js/html5shiv.min.js"></script>
  <![endif]-->
  
        <script data-url_root="../" id="documentation_options" src="../_static/documentation_options.js"></script>
        <script src="../_static/jquery.js"></script>
        <script src="../_static/underscore.js"></script>
        <script src="../_static/doctools.js"></script>
    <script src="../_static/js/theme.js"></script>
    <link rel="index" title="Index" href="../genindex.html" />
    <link rel="search" title="Search" href="../search.html" />
    <link rel="next" title="minos.saga.manager module" href="minos.saga.manager.html" />
    <link rel="prev" title="minos.saga.context module" href="minos.saga.context.html" />
    <link href="../_static/style.css" rel="stylesheet" type="text/css">

</head>

<body class="wy-body-for-nav"> 
  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >
            <a href="../index.html" class="icon icon-home"> Minos Microservice Saga
          </a>
              <div class="version">
                0.6.0
              </div>
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="../search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>
        </div><div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="Navigation menu">
              <ul class="current">
<li class="toctree-l1"><a class="reference internal" href="../readme.html">Introduction</a></li>
<li class="toctree-l1"><a class="reference internal" href="../runthetests.html">Run the tests</a></li>
<li class="toctree-l1"><a class="reference internal" href="../usage.html">Usage</a></li>
<li class="toctree-l1 current"><a class="reference internal" href="minos.html">minos namespace</a><ul class="current">
<li class="toctree-l2 current"><a class="reference internal" href="minos.html#subpackages">Subpackages</a><ul class="current">
<li class="toctree-l3 current"><a class="reference internal" href="minos.saga.html">minos.saga package</a><ul class="current">
<li class="toctree-l4"><a class="reference internal" href="minos.saga.html#subpackages">Subpackages</a></li>
<li class="toctree-l4 current"><a class="reference internal" href="minos.saga.html#submodules">Submodules</a></li>
</ul>
</li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l1"><a class="reference internal" href="../history.html">History</a></li>
</ul>

        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap"><nav class="wy-nav-top" aria-label="Mobile navigation menu" >
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../index.html">Minos Microservice Saga</a>
      </nav>

      <div class="wy-nav-content">
        <div class="rst-content">
          <div role="navigation" aria-label="Page navigation">
  <ul class="wy-breadcrumbs">
      <li><a href="../index.html" class="icon icon-home"></a> &raquo;</li>
          <li><a href="minos.html">minos namespace</a> &raquo;</li>
          <li><a href="minos.saga.html">minos.saga package</a> &raquo;</li>
      <li>minos.saga.exceptions module</li>
      <li class="wy-breadcrumbs-aside">
            <a href="../_sources/api/minos.saga.exceptions.rst.txt" rel="nofollow"> View page source</a>
      </li>
  </ul>
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
             
  <section id="module-minos.saga.exceptions">
<span id="minos-saga-exceptions-module"></span><h1>minos.saga.exceptions module<a class="headerlink" href="#module-minos.saga.exceptions" title="Permalink to this headline"></a></h1>
<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.AlreadyCommittedException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">AlreadyCommittedException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#AlreadyCommittedException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.AlreadyCommittedException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaException" title="minos.saga.exceptions.SagaException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaException</span></code></a></p>
<p>Exception to be raised when trying to modifying an already committed saga.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.AlreadyCommittedException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.AlreadyCommittedException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.AlreadyCommittedException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.AlreadyCommittedException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.AlreadyCommittedException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.AlreadyCommittedException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.AlreadyOnSagaException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">AlreadyOnSagaException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#AlreadyOnSagaException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.AlreadyOnSagaException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaStepException" title="minos.saga.exceptions.SagaStepException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaStepException</span></code></a></p>
<p>Exception to be raised when a saga step is already in another saga.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.AlreadyOnSagaException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#AlreadyOnSagaException.__init__"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.AlreadyOnSagaException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.AlreadyOnSagaException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.AlreadyOnSagaException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.AlreadyOnSagaException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.AlreadyOnSagaException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.EmptySagaException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">EmptySagaException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#EmptySagaException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.EmptySagaException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaException" title="minos.saga.exceptions.SagaException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaException</span></code></a></p>
<p>Exception to be raised when saga is empty.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.EmptySagaException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#EmptySagaException.__init__"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.EmptySagaException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.EmptySagaException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.EmptySagaException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.EmptySagaException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.EmptySagaException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.EmptySagaStepException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">EmptySagaStepException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#EmptySagaStepException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.EmptySagaStepException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaStepException" title="minos.saga.exceptions.SagaStepException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaStepException</span></code></a></p>
<p>Exception to be raised when the step is empty.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.EmptySagaStepException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#EmptySagaStepException.__init__"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.EmptySagaStepException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.EmptySagaStepException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.EmptySagaStepException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.EmptySagaStepException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.EmptySagaStepException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.ExecutorException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">ExecutorException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">exception</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#ExecutorException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.ExecutorException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaException" title="minos.saga.exceptions.SagaException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaException</span></code></a></p>
<p>Exception to be raised when a saga executor raises some exception.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.ExecutorException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">exception</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#ExecutorException.__init__"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.ExecutorException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.ExecutorException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.ExecutorException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.ExecutorException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.ExecutorException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleElseThenException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">MultipleElseThenException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#MultipleElseThenException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.MultipleElseThenException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaStepException" title="minos.saga.exceptions.SagaStepException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaStepException</span></code></a></p>
<p>Exception to be raised when multiple else then alternatives are defined.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleElseThenException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#MultipleElseThenException.__init__"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.MultipleElseThenException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleElseThenException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.MultipleElseThenException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleElseThenException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.MultipleElseThenException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleOnErrorException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">MultipleOnErrorException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#MultipleOnErrorException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.MultipleOnErrorException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaStepException" title="minos.saga.exceptions.SagaStepException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaStepException</span></code></a></p>
<p>Exception to be raised when multiple on error methods are defined.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleOnErrorException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#MultipleOnErrorException.__init__"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.MultipleOnErrorException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleOnErrorException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.MultipleOnErrorException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleOnErrorException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.MultipleOnErrorException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleOnExecuteException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">MultipleOnExecuteException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#MultipleOnExecuteException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.MultipleOnExecuteException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaStepException" title="minos.saga.exceptions.SagaStepException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaStepException</span></code></a></p>
<p>Exception to be raised when multiple on execute methods are defined.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleOnExecuteException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#MultipleOnExecuteException.__init__"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.MultipleOnExecuteException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleOnExecuteException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.MultipleOnExecuteException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleOnExecuteException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.MultipleOnExecuteException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleOnFailureException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">MultipleOnFailureException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#MultipleOnFailureException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.MultipleOnFailureException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaStepException" title="minos.saga.exceptions.SagaStepException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaStepException</span></code></a></p>
<p>Exception to be raised when multiple on failure methods are defined.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleOnFailureException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#MultipleOnFailureException.__init__"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.MultipleOnFailureException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleOnFailureException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.MultipleOnFailureException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleOnFailureException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.MultipleOnFailureException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleOnSuccessException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">MultipleOnSuccessException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#MultipleOnSuccessException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.MultipleOnSuccessException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaStepException" title="minos.saga.exceptions.SagaStepException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaStepException</span></code></a></p>
<p>Exception to be raised when multiple on success methods are defined.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleOnSuccessException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#MultipleOnSuccessException.__init__"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.MultipleOnSuccessException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleOnSuccessException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.MultipleOnSuccessException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.MultipleOnSuccessException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.MultipleOnSuccessException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">SagaException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <code class="xref py py-class docutils literal notranslate"><span class="pre">minos.common.exceptions.MinosException</span></code></p>
<p>Base saga exception.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.SagaException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaExecutionAlreadyExecutedException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">SagaExecutionAlreadyExecutedException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaExecutionAlreadyExecutedException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaExecutionAlreadyExecutedException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaExecutionException" title="minos.saga.exceptions.SagaExecutionException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaExecutionException</span></code></a></p>
<p>Exception to be raised when a saga execution cannot be executed.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaExecutionAlreadyExecutedException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaExecutionAlreadyExecutedException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaExecutionAlreadyExecutedException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.SagaExecutionAlreadyExecutedException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaExecutionAlreadyExecutedException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaExecutionAlreadyExecutedException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaExecutionException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">SagaExecutionException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaExecutionException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaExecutionException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaException" title="minos.saga.exceptions.SagaException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaException</span></code></a></p>
<p>Base exception for saga execution.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaExecutionException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaExecutionException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaExecutionException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.SagaExecutionException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaExecutionException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaExecutionException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaExecutionNotFoundException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">SagaExecutionNotFoundException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaExecutionNotFoundException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaExecutionNotFoundException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaExecutionException" title="minos.saga.exceptions.SagaExecutionException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaExecutionException</span></code></a></p>
<p>Exception to be raised when a saga execution is not found.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaExecutionNotFoundException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaExecutionNotFoundException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaExecutionNotFoundException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.SagaExecutionNotFoundException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaExecutionNotFoundException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaExecutionNotFoundException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaFailedCommitCallbackException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">SagaFailedCommitCallbackException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">exception</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaFailedCommitCallbackException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaFailedCommitCallbackException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaFailedExecutionException" title="minos.saga.exceptions.SagaFailedExecutionException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaFailedExecutionException</span></code></a></p>
<p>Exception to be raised when a saga commit callback raises some exception</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaFailedCommitCallbackException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">exception</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaFailedCommitCallbackException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaFailedCommitCallbackException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.SagaFailedCommitCallbackException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaFailedCommitCallbackException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaFailedCommitCallbackException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaFailedExecutionException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">SagaFailedExecutionException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">exception</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaFailedExecutionException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaFailedExecutionException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaExecutionException" title="minos.saga.exceptions.SagaExecutionException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaExecutionException</span></code></a></p>
<p>Exception to be raised when a saga execution failed while running.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaFailedExecutionException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">exception</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaFailedExecutionException.__init__"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaFailedExecutionException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaFailedExecutionException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.SagaFailedExecutionException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaFailedExecutionException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaFailedExecutionException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaFailedExecutionStepException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">SagaFailedExecutionStepException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">exception</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaFailedExecutionStepException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaFailedExecutionStepException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaStepExecutionException" title="minos.saga.exceptions.SagaStepExecutionException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaStepExecutionException</span></code></a>, <a class="reference internal" href="#minos.saga.exceptions.SagaFailedExecutionException" title="minos.saga.exceptions.SagaFailedExecutionException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaFailedExecutionException</span></code></a></p>
<p>Exception to be raised when a saga execution step failed while running.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaFailedExecutionStepException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">exception</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaFailedExecutionStepException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaFailedExecutionStepException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.SagaFailedExecutionStepException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaFailedExecutionStepException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaFailedExecutionStepException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaNotCommittedException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">SagaNotCommittedException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaNotCommittedException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaNotCommittedException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaException" title="minos.saga.exceptions.SagaException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaException</span></code></a></p>
<p>Exception to be raised when trying to exec a  not committed saga.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaNotCommittedException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaNotCommittedException.__init__"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaNotCommittedException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaNotCommittedException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.SagaNotCommittedException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaNotCommittedException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaNotCommittedException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaNotDefinedException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">SagaNotDefinedException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaNotDefinedException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaNotDefinedException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaStepException" title="minos.saga.exceptions.SagaStepException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaStepException</span></code></a></p>
<p>Exception to be raised when the saga is not defined.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaNotDefinedException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaNotDefinedException.__init__"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaNotDefinedException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaNotDefinedException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.SagaNotDefinedException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaNotDefinedException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaNotDefinedException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaPausedExecutionStepException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">SagaPausedExecutionStepException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaPausedExecutionStepException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaPausedExecutionStepException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaStepExecutionException" title="minos.saga.exceptions.SagaStepExecutionException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaStepExecutionException</span></code></a></p>
<p>Exception to be raised when a saga execution step is paused.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaPausedExecutionStepException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaPausedExecutionStepException.__init__"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaPausedExecutionStepException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaPausedExecutionStepException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.SagaPausedExecutionStepException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaPausedExecutionStepException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaPausedExecutionStepException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaResponseException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">SagaResponseException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaResponseException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaResponseException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaException" title="minos.saga.exceptions.SagaException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaException</span></code></a></p>
<p>Exception to be used when <code class="docutils literal notranslate"><span class="pre">CommandStatus</span></code> is not <code class="docutils literal notranslate"><span class="pre">SUCCESS</span></code></p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaResponseException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaResponseException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaResponseException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.SagaResponseException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaResponseException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaResponseException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaRollbackExecutionException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">SagaRollbackExecutionException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaRollbackExecutionException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaRollbackExecutionException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaExecutionException" title="minos.saga.exceptions.SagaExecutionException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaExecutionException</span></code></a></p>
<p>Exception to be raised when a saga exception cannot be rollbacked</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaRollbackExecutionException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaRollbackExecutionException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaRollbackExecutionException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.SagaRollbackExecutionException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaRollbackExecutionException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaRollbackExecutionException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaRollbackExecutionStepException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">SagaRollbackExecutionStepException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaRollbackExecutionStepException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaRollbackExecutionStepException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaStepExecutionException" title="minos.saga.exceptions.SagaStepExecutionException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaStepExecutionException</span></code></a></p>
<p>Exception to be raised when a saga execution step failed while performing a rollback.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaRollbackExecutionStepException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaRollbackExecutionStepException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaRollbackExecutionStepException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.SagaRollbackExecutionStepException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaRollbackExecutionStepException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaRollbackExecutionStepException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaStepException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">SagaStepException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaStepException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaStepException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaException" title="minos.saga.exceptions.SagaException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaException</span></code></a></p>
<p>Base exception for saga steps.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaStepException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaStepException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaStepException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.SagaStepException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaStepException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaStepException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaStepExecutionException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">SagaStepExecutionException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#SagaStepExecutionException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.SagaStepExecutionException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaException" title="minos.saga.exceptions.SagaException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaException</span></code></a></p>
<p>Base exception for saga execution step.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaStepExecutionException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">error_message</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaStepExecutionException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaStepExecutionException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.SagaStepExecutionException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.SagaStepExecutionException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.SagaStepExecutionException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

<dl class="py exception">
<dt class="sig sig-object py" id="minos.saga.exceptions.UndefinedOnExecuteException">
<em class="property"><span class="pre">exception</span><span class="w"> </span></em><span class="sig-prename descclassname"><span class="pre">minos.saga.exceptions.</span></span><span class="sig-name descname"><span class="pre">UndefinedOnExecuteException</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#UndefinedOnExecuteException"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.UndefinedOnExecuteException" title="Permalink to this definition"></a></dt>
<dd><p>Bases: <a class="reference internal" href="#minos.saga.exceptions.SagaStepException" title="minos.saga.exceptions.SagaStepException"><code class="xref py py-class docutils literal notranslate"><span class="pre">minos.saga.exceptions.SagaStepException</span></code></a></p>
<p>Exception to be raised when the on execute method is not defined.</p>
<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.UndefinedOnExecuteException.__init__">
<span class="sig-name descname"><span class="pre">__init__</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">message</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">None</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="../_modules/minos/saga/exceptions.html#UndefinedOnExecuteException.__init__"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#minos.saga.exceptions.UndefinedOnExecuteException.__init__" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py attribute">
<dt class="sig sig-object py" id="minos.saga.exceptions.UndefinedOnExecuteException.args">
<span class="sig-name descname"><span class="pre">args</span></span><a class="headerlink" href="#minos.saga.exceptions.UndefinedOnExecuteException.args" title="Permalink to this definition"></a></dt>
<dd></dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="minos.saga.exceptions.UndefinedOnExecuteException.with_traceback">
<span class="sig-name descname"><span class="pre">with_traceback</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span><a class="headerlink" href="#minos.saga.exceptions.UndefinedOnExecuteException.with_traceback" title="Permalink to this definition"></a></dt>
<dd><p>Exception.with_traceback(tb) –
set self.__traceback__ to tb and return self.</p>
</dd></dl>

</dd></dl>

</section>


           </div>
          </div>
          <footer><div class="rst-footer-buttons" role="navigation" aria-label="Footer">
        <a href="minos.saga.context.html" class="btn btn-neutral float-left" title="minos.saga.context module" accesskey="p" rel="prev"><span class="fa fa-arrow-circle-left" aria-hidden="true"></span> Previous</a>
        <a href="minos.saga.manager.html" class="btn btn-neutral float-right" title="minos.saga.manager module" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right" aria-hidden="true"></span></a>
    </div>

  <hr/>

  <div role="contentinfo">
    <p>&#169; Copyright 2021, Clariteia.</p>
  </div>

  Built with <a href="https://www.sphinx-doc.org/">Sphinx</a> using a
    <a href="https://github.com/readthedocs/sphinx_rtd_theme">theme</a>
    provided by <a href="https://readthedocs.org">Read the Docs</a>.
   

</footer>
        </div>
      </div>
    </section>
  </div>
  <script>
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script> 

</body>
</html>